# Default values for fabric-logger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: splunkdlt/fabric-logger
  tag: release-3.0.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

fabric:
  blockType: full
  discovery: false
  asLocalhost: false

secrets:
  peer:
    # If create: is set to true, then secrets will be auto created based on a cryptogen MSP directory structure.
    create: false
    # Secrets can be specified here to overwrite the secret creation setting above.
    # cert: hlf--peer-admincert
    # itemKey can be defined if there is a secret with multiple items stored inside.
    # certItem: cert.pem
    # key: hlf--peer-adminkey
    # keyItem: key.pem
    # tls: hlf--peer-tlscert
    # tlsItem: tlscacert.pem
    # clientCert: hlf--peer-clientcert
    # clientCertItem: clientCert.pem
    # clientKey: hlf--peer-clientkey
    # clientKeyItem: clientKey.pem

loggingLocation: splunk
splunk:
  hec:
    token: 00000000-0000-0000-0000-000000000000
    url: https://splunk.example.com:8088
    rejectInvalidCerts: "false"
  index: hyperledger_logs

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
