# Default values for fabric-logger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: splunkdlt/fabric-logger
  tag: release-3.0.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

fabric:
  msp: ButtercupMSP
  orgDomain: buttercup.example.com
  blockType: full
  user: Admin
  channels:
    - buttercup-go
    - haunt
    - crisis-uprising
    - containment-apocalyse
    - rage-trilogy
    - chaos-oath
  ccevents:
    # A list of chaincode events to listen for:
    - channelName: buttercup-go
      chaincodeId: splunk_cc

secrets:
  peer:
    # If create: is set to true, then secrets will be auto created based on a cryptogen MSP directory structure.
    create: true
    # Secrets can be specified here to overwrite the secret creation setting above.


loggingLocation: splunk
splunk:
  hec:
    token: 12345678-ABCD-EFGH-IJKL-123456789012
    url: https://splunk-splunk-kube:8088
    rejectInvalidCerts: "false"
  index: hyperledger_logs

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: fabric-logger.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
