apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fabric-logger.name" . }}-network-config
data:
  network.yaml: |-
    name: "Network"
    version: "1.0"
    client:
      {{ toYaml .Values.client }}
    channels:
      {{- range $key, $value:=.Values.channels }}
      {{ $key }}:
        peers:
        {{- range .peers }}
          {{ . }}:
        {{- end }}
      {{- end }}
    organizations:
      {{- range $key, $value:= .Values.organizations }}
      {{ $key }}:
        mspid: {{ .mspid }}
        peers:
          {{- range .peers }}
          - {{ . }}
          {{- end }}
      {{- end }}
    peers:
      {{- range $key, $value:= .Values.peers }}
      {{ $key }}:
        url: {{ .url }}
        grpcOption:
        {{- range $key,$value:= .grpcOptions }}
          {{ $key }}: {{ toYaml $value }}
        {{- end }}
        tlsCACerts:
          path: /var/hyperledger/msp/tlscacert/tlscacert.pem
      {{- end }}

  fabriclogger.yaml: |-
    fabric:
      blockType: {{ .Values.fabric.blockType }}
      discovery: {{ .Values.fabric.discovery }}
      asLocalhost: {{ .Values.fabric.asLocalhost }}
      user: {{ .Values.fabric.user }}
      channels:
        {{- range .Values.fabric.channels }}
        - {{ . }}
        {{- end }}
      ccevents:
        {{- range .Values.fabric.ccevents }}
        - channelName: {{ .channelName }}
          chaincodeId: {{ .chaincodeId }}
        {{- end }}