apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fabric-logger.name" . }}-{{ .Values.peer.peerName }}
  labels:
    app.kubernetes.io/name: {{ include "fabric-logger.name" . }}
    helm.sh/chart: {{ include "fabric-logger.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fabric-logger.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fabric-logger.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["fabriclogger"]
          args: ["-c", "network/fabriclogger.yaml"]
          volumeMounts:
            - name: network
              mountPath: /usr/src/app/network
            {{- if or .Values.secrets.peer.cert .Values.secrets.peer.create }}
            - mountPath: /var/hyperledger/msp/signcerts
              name: id-cert
            {{- end }}
            {{- if or .Values.secrets.peer.key .Values.secrets.peer.create }}
            - mountPath: /var/hyperledger/msp/keystore
              name: id-key
            {{- end }}
            {{- if or .Values.secrets.peer.tls .Values.secrets.peer.create }}
            - mountPath: /var/hyperledger/msp/tlscacert
              name: tls-cert
            {{- end }}
            {{- if or .Values.secrets.peer.clientCert .Values.secrets.peer.create }}
            - mountPath: "/var/hyperledger/tls/signcerts"
              name: id-clientcert
            {{- end }}
            {{- if or .Values.secrets.peer.clientKey .Values.secrets.peer.create }}
            - mountPath: "/var/hyperledger/tls/keystore"
              name: id-clientkey
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: FABRIC_KEYFILE
            value: "/var/hyperledger/msp/keystore/key.pem"
          - name: FABRIC_CERTFILE
            value: "/var/hyperledger/msp/signcerts/cert.pem"
          {{- if or .Values.secrets.peer.clientCert .Values.secrets.peer.create }}
          - name: FABRIC_CLIENT_CERTFILE
            value: "/var/hyperledger/tls/signcerts/clientCert.pem"
          {{- end }}
          {{- if or .Values.secrets.peer.clientKey .Values.secrets.peer.create }}
          - name: FABRIC_CLIENT_KEYFILE
            value: "/var/hyperledger/tls/keystore/clientKey.pem"
          {{- end }}
          - name: FABRIC_MSP
            value: {{ .Values.peer.mspName | quote }}
          - name: FABRIC_PEER
            value: {{ .Values.peer.peerName | quote }}
          - name: FABRIC_LOGGER_USERNAME
            value: {{ .Values.peer.username | quote }}
          - name: SPLUNK_HEC_TOKEN
            value: {{ .Values.splunk.hec.token | quote }}
          - name: SPLUNK_HEC_URL
            value: {{ .Values.splunk.hec.url | quote }}
          - name: SPLUNK_HOST
            value: {{ .Values.splunk.hec.host | quote }}
          - name: SPLUNK_PORT
            value: {{ .Values.splunk.hec.port | quote }}
          - name: SPLUNK_INDEX
            value: {{ .Values.splunk.index | quote }}
          - name: LOGGING_LOCATION
            value: {{ .Values.loggingLocation | quote }}
          - name: NETWORK_CONFIG
            value: network/network.yaml
          - name: SPLUNK_HEC_REJECT_INVALID_CERTS
            value: {{ .Values.splunk.hec.rejectInvalidCerts | quote }}
      volumes:
      - name: network 
        configMap:
          name: {{ include "fabric-logger.name" . }}-{{ .Values.peer.peerName }}-network-config

      {{- if .Values.secrets.peer.cert }}
      - name: id-cert
        secret:
          secretName: {{ .Values.secrets.peer.cert }}
          {{- if .Values.secrets.peer.certItem }}
          items:
            - key: {{ .Values.secrets.peer.certItem }}
              path: cert.pem
          {{- end }}
      {{- else if .Values.secrets.peer.create }}
      - name: id-cert
        secret:
          secretName: fabric-logger--{{ .Values.peer.orgDomain | lower }}--{{ .Values.peer.peerName  | lower }}-msp
          items:
            - key: cert.pem
              path: cert.pem
      {{- end }}

      {{- if .Values.secrets.peer.key }}
      - name: id-key
        secret:
          secretName: {{ .Values.secrets.peer.key }}
          {{- if .Values.secrets.peer.keyItem }}
          items:
            - key: {{ .Values.secrets.peer.keyItem }}
              path: key.pem
          {{- end }}
      {{- else if .Values.secrets.peer.create }}
      - name: id-key
        secret:
          secretName: fabric-logger--{{ .Values.peer.orgDomain | lower }}--{{ .Values.peer.peerName  | lower }}-msp
          items:
            - key: key.pem
              path: key.pem
      {{- end }}

      {{- if .Values.secrets.peer.tls }}
      - name: tls-cert
        secret:
          secretName: {{ .Values.secrets.peer.tls }}
          {{- if .Values.secrets.peer.tlsItem }}
          items:
            - key: {{ .Values.secrets.peer.tlsItem }}
              path: tlscacert.pem
          {{- end }}
      {{- else if .Values.secrets.peer.create }}
      - name: tls-cert
        secret:
          secretName: fabric-logger--{{ .Values.peer.orgDomain | lower }}--{{ .Values.peer.peerName  | lower }}-msp
          items:
            - key: tlscacert.pem
              path: tlscacert.pem
      {{- end }}

      {{- if .Values.secrets.peer.clientKey }}
      - name: id-clientkey
        secret:
          secretName: {{ .Values.secrets.peer.clientKey }}
          {{- if .Values.secrets.peer.clientKeyItem }}
          items:
            - key: {{ .Values.secrets.peer.clientKeyItem }}
              path: clientKey.pem
          {{- end }}
      {{- else if .Values.secrets.peer.create }}
      - name: id-clientkey
        secret:
          secretName: fabric-logger--{{ .Values.peer.orgDomain | lower }}--{{ .Values.peer.peerName  | lower }}-msp
          items:
            - key: clientKey.pem
              path: clientKey.pem
      {{- end}}

      {{- if .Values.secrets.peer.clientCert }}
      - name: id-clientcert
        secret:
          secretName: {{ .Values.secrets.peer.clientCert }}
          {{- if .Values.secrets.peer.clientCertItem }}
          items:
            - key: {{ .Values.secrets.peer.clientCertItem }}
              path: clientCert.pem
          {{- end }}
      {{- else if .Values.secrets.peer.create }}
      - name: id-clientcert
        secret:
          secretName: fabric-logger--{{ .Values.peer.orgDomain | lower }}--{{ .Values.peer.peerName  | lower }}-msp
          items:
            - key: clientCert.pem
              path: clientCert.pem
      {{- end }}
      {{- if $.Values.hostAliases }}
      hostAliases:
      {{- range $i, $alias := $.Values.hostAliases }}
      - ip: {{ $alias.ip }}
        hostnames: {{ $alias.hostnames }}
      {{- end }}
      {{- end }}{{""}}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
