{{- if .Values.secrets.peer.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: fabric-logger--{{ .Values.fabric.orgDomain | lower }}-msp
  labels:
    orgDomain: {{ .Values.fabric.orgDomain }}
data:
  cert.pem: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/users/%s@%s/msp/signcerts/%s@%s-cert.pem" .Values.fabric.orgDomain .Values.fabric.user .Values.fabric.orgDomain .Values.fabric.user .Values.fabric.orgDomain ) | b64enc }}
  tlscacert.pem: |- 
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/users/%s@%s/msp/tlscacerts/tlsca.%s-cert.pem" .Values.fabric.orgDomain .Values.fabric.user .Values.fabric.orgDomain .Values.fabric.orgDomain ) | b64enc }}
  {{- range $path, $bytes := $.Files.Glob (printf "crypto-config/peerOrganizations/%s/users/%s@%s/msp/keystore/*" .Values.fabric.orgDomain .Values.fabric.user .Values.fabric.orgDomain ) }}
  key.pem: |-
      {{ $.Files.Get $path | b64enc }}
  {{- end }}
  clientCert.pem: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/users/%s@%s/tls/client.crt" .Values.fabric.orgDomain .Values.fabric.user .Values.fabric.orgDomain ) | b64enc }}
  clientKey.pem: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/users/%s@%s/tls/client.key" .Values.fabric.orgDomain .Values.fabric.user .Values.fabric.orgDomain ) | b64enc }}
{{- end}}